#This config file will be responsible for acting as our baseline -- runs against production, on main pages used for regression

#TODO

#Headless browser option
browser:
  webkit: "phantomjs"
  # gecko: "slimerjs"

device:
  base: firefox
  compare: firefox

#If you want to have multiple snapping files, set the file name here
snap_file: "lib/wraith/javascript/snap.js"

# Type the name of the directory that shots will be stored in
directory:
  - 'production-vs-staging'

# Add only 2 domains, key will act as a label
domains:
  production: "http://www.lessonplanet.com"
  staging: "http://staging.lessonplanet.com"

#Type screen widths below, here are a couple of examples
screen_widths:
#  - 1440x900
  - 1280x1024
  - 1024x768
  - 768x1024
  - 320x480


#Type page URL paths below, here are a couple of examples
paths:
  home: /
  search: /search?keywords=peaches&grade_ids%5B%5D=249&subject_ids%5B%5D=365216&type_ids%5B%5D=357917
  apps: /apps
  edtech: /professional-development/courses
  how-it-works: /content/how_it_works
  school_edition: /schooledition
  signup: /subscription/new
  standards: /state-standards

# If you don't want to name the paths explicitly you can use a yaml
# collection as follows, and names will be derived by replacing / with _
#
# paths:
#  - /imghp
#  - /maps

#Amount of fuzz ImageMagick will use
fuzz: '20%'

#Set the number of days to keep the site spider file
spider_days:
  - 10

#Tell PhantomJS to ignore SSL errors:
phantomjs_options: "--ignore-ssl-errors=true"
