##############################################################
##############################################################
# This is an example configuration provided by Wraith.
# Feel free to amend for your own requirements.
# ---
# This particular config is intended to demonstrate how
# to use Wraith in 'history' mode, which is best suited to
# making sure your site's appearance remains consistent over
# time.
#
# `wraith history history.yaml` # generate base screenshots
# `wraith latest history.yaml`  # take new shots and compare
#
##############################################################
##############################################################

# (required) The engine to run Wraith with. Examples: 'phantomjs', 'casperjs', 'slimerjs'
browser: "phantomjs"

# (required) The domain to take screenshots of.
domains:
  production: "http://www.lessonplanet.com"
  staging: "http://staging.lessonplanet.com"

# (required) The paths to capture. This particular config is using casperjs, so we can take screenshots of selectors rather than the entire page.
paths:
   home: /
   search: /search?keywords=peaches&grade_ids[]=249&subject_ids[]=365220
   directory: /lesson-plans
   apps: /apps
   edtech: /professional-development/courses
   how_it_works: /content/how_it_works
   school_edition: /schooledition
   signup: /subscription/new
   sign_in: /auth/users/sign_in
   standards: /state-standards
   contact_us: /us/contact
   calendar: /calendar
   about_us: /us/about_us
   videos: /us/videos
   testimonials: /us/testimonials

# (optional) JavaScript file to execute before taking screenshot of every path. Default: nil
before_capture: 'javascript/cookies_and_headers--phantom.js'

# (required) Screen widths (and optional height) to resize the browser to before taking the screenshot.
screen_widths:
  - 750x1334
  - 800x600
  - 960x640
  - 1024x768
  - 1136x640
  - 1242x2208
  - 1280x720
  - 1366x768
  - 1440x900
  - 1680x1050
  - 1900x1200
  - 1920x1200
  - 2048x1536
  - 2560x1600
  - 2739x1824
  - 2880x1800

# (optional) Resize to each screen width (efficient), or reload at each screen width (costly). Default: 'reload'
resize_or_reload: 'reload'

# (required for history mode, otherwise optional) The directory that your base screenshots will be stored in.
history_dir: 'shots_history'

# (required) The directory that your latest screenshots will be stored in
directory: 'shots'

# (required) Amount of fuzz ImageMagick will use when comparing images. A higher fuzz makes the comparison less strict.
fuzz: '20%'

# (optional) The maximum acceptable level of difference (in %) between two images before Wraith reports a failure. Default: 0
threshold: 0

# (optional) Specify the template (and generated thumbnail sizes) for the gallery output.
gallery:
  template: 'basic_template' # Examples: 'basic_template' (default), 'slideshow_template'
  thumb_width:  200
  thumb_height: 200

# (optional) Choose which results are displayed in the gallery, and in what order. Default: alphanumeric
# Options:
#   alphanumeric - all paths (with or without a difference) are shown, sorted by path
#   diffs_first - all paths (with or without a difference) are shown, sorted by difference size (largest first)
#   diffs_only - only paths with a difference are shown, sorted by difference size (largest first)
# Note: different screen widths are always grouped together.
mode: alphanumeric

# (optional) Choose to run Wraith in verbose mode, for easier debugging. Default: false
verbose: false

# (optional) Color to highlight the image diff. Default: 'blue'
highlight_color: blue

# (optional) Parameters to pass to Phantom/Casper command line. Default: '--ignore-ssl-errors=true --ssl-protocol=tlsv1'
phantomjs_options: '--ignore-ssl-errors=true --ssl-protocol=any'
